export const Config = {
  // 기존 키
  KAKAO_REST_API_KEY: process.env.KAKAO_REST_API_KEY,
  JUSO_CONFM_KEY: process.env.JUSO_CONFM_KEY,
  DATA_GO_KR_API_KEY: process.env.DATA_GO_KR_API_KEY,
  KAKAO_JAVASCRIPT_KEY: process.env.KAKAO_JAVASCRIPT_KEY,
  KAKAO_NATIVE_APP_KEY: process.env.KAKAO_NATIVE_APP_KEY,
  GEMINI_API_KEY: process.env.GEMINI_API_KEY,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_URI: process.env.GOOGLE_REDIRECT_URI,
  // 새로 추가된 키
  ALLOWED_EMAILS: process.env.ALLOWED_EMAILS,
  ADMIN_EMAILS: process.env.ADMIN_EMAILS,
  ENABLE_BOOTSTRAP_ADMIN: process.env.ENABLE_BOOTSTRAP_ADMIN,
  // 서버 설정
  PORT: process.env.PORT,
  HOST: process.env.HOST,
  TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN,
  TELEGRAM_CHAT_ID: process.env.TELEGRAM_CHAT_ID,
  // 데이터 및 서비스 설정
  GRAPH_DB_ENABLED: process.env.GRAPH_DB_ENABLED,
  CHECK_INTERVAL_SECONDS: process.env.CHECK_INTERVAL_SECONDS,
};
